# CI de nível de deploy, para executar comandos pós-deploy

# nome pepiline

name: "Execução via push"

on:
  push:
    branches:
     - main

jobs:
  tests-unitarios:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4 # para fazer checkout do código
  
     - uses: actions/setup-node@v4
       with:
          node-version: 24.x
      
     - name: Instalando dependências
       run: npm install
      
     - name: Executando testes unitários
       run: npm run test
      
      